#include "VehiclePhATMirrorUtils.h"
#include "VehiclePhATBodyUtils.h"
#include "PhysicsEngine/PhysicsAsset.h"
#include "PhysicsEngine/SkeletalBodySetup.h"
#include "PhysicsEngine/AggregateGeom.h"
#include "ScopedTransaction.h"

FString FVehiclePhATMirrorUtils::PatternToToken(const FString& P){FString T=P; T.ReplaceInline(TEXT("*"),TEXT("")); return T;}
FName FVehiclePhATMirrorUtils::MakeTargetName(FName S,const FString& SP,const FString& TP){FString N=S.ToString(); N.ReplaceInline(*PatternToToken(SP),*PatternToToken(TP),ESearchCase::IgnoreCase); return FName(*N);}
FVector FVehiclePhATMirrorUtils::MirrorVector(const FVector& V,EVehiclePhATMirrorAxis A){FVector R=V; if(A==EVehiclePhATMirrorAxis::X)R.X*=-1; else if(A==EVehiclePhATMirrorAxis::Y)R.Y*=-1; else R.Z*=-1; return R;}
FQuat FVehiclePhATMirrorUtils::MirrorQuat(const FQuat& Q,EVehiclePhATMirrorAxis A){FMatrix M=FQuatRotationMatrix(Q); FVector X=MirrorVector(M.GetScaledAxis(EAxis::X),A),Y=MirrorVector(M.GetScaledAxis(EAxis::Y),A),Z=MirrorVector(M.GetScaledAxis(EAxis::Z),A); if(A==EVehiclePhATMirrorAxis::X)X*=-1; else if(A==EVehiclePhATMirrorAxis::Y)Y*=-1; else Z*=-1; return FRotationMatrix::MakeFromXZ(X,Z).ToQuat();}
void FVehiclePhATMirrorUtils::MirrorAggGeom(FKAggregateGeom& G,const FVehiclePhATMirrorOptions& O){auto MT=[&](FTransform T){ if(O.bMirrorLocation)T.SetLocation(MirrorVector(T.GetLocation(),O.Axis)); if(O.bMirrorRotation)T.SetRotation(MirrorQuat(T.GetRotation(),O.Axis)); return T;}; for(auto& E:G.BoxElems)E.SetTransform(MT(E.GetTransform())); for(auto& E:G.SphylElems)E.SetTransform(MT(E.GetTransform())); for(auto& E:G.TaperedCapsuleElems)E.SetTransform(MT(E.GetTransform())); for(auto& E:G.SphereElems)if(O.bMirrorLocation)E.Center=MirrorVector(E.Center,O.Axis); for(auto& E:G.ConvexElems){E.SetTransform(MT(E.GetTransform())); for(FVector& V:E.VertexData)if(O.bMirrorLocation)V=MirrorVector(V,O.Axis); E.UpdateElemBox();}}
TArray<FVehiclePhATBodyPair> FVehiclePhATMirrorUtils::BuildMirrorPairs(UPhysicsAsset* P,const FVehiclePhATMirrorOptions& O){TArray<FVehiclePhATBodyPair> R; FString Tok=PatternToToken(O.SourcePattern); for(FName B:FVehiclePhATBodyUtils::GetSkeletonBoneNames(P)){ if(!B.ToString().Contains(Tok,ESearchCase::IgnoreCase))continue; FVehiclePhATBodyPair Pair; Pair.SourceBone=B; Pair.TargetBone=MakeTargetName(B,O.SourcePattern,O.TargetPattern); Pair.bSourceBodyExists=FVehiclePhATBodyUtils::FindBodySetup(P,B)!=nullptr; Pair.bTargetBodyExists=FVehiclePhATBodyUtils::FindBodySetup(P,Pair.TargetBone)!=nullptr; Pair.bTargetBoneExists=FVehiclePhATBodyUtils::GetSkeletonBoneNames(P).Contains(Pair.TargetBone); Pair.PreviewText=FString::Printf(TEXT("%s -> %s"),*B.ToString(),*Pair.TargetBone.ToString()); Pair.bSelected=Pair.bSourceBodyExists&&Pair.bTargetBoneExists; R.Add(Pair);} return R;}
bool FVehiclePhATMirrorUtils::ApplyMirror(UPhysicsAsset* P,const FVehiclePhATMirrorOptions& O,const TArray<FVehiclePhATBodyPair>& Pairs,FString& Msg){ if(!P)return false; FScopedTransaction Tx(NSLOCTEXT("VehiclePhATTools","MirrorBodies","Mirror Vehicle Physics Bodies")); P->Modify(); int32 Count=0; for(const auto& Pair:Pairs){ if(!Pair.bSelected)continue; USkeletalBodySetup* S=FVehiclePhATBodyUtils::FindBodySetup(P,Pair.SourceBone); if(!S)continue; USkeletalBodySetup* T=FVehiclePhATBodyUtils::FindBodySetup(P,Pair.TargetBone); if(T&&!O.bReplaceExistingTargetBodies)continue; if(!T&&O.bCreateMissingTargetBodies){T=NewObject<USkeletalBodySetup>(P,NAME_None,RF_Transactional); P->SkeletalBodySetups.Add(T);} if(!T)continue; T->Modify(); T->CopyBodyPropertiesFrom(S); T->BoneName=Pair.TargetBone; T->AggGeom=S->AggGeom; MirrorAggGeom(T->AggGeom,O); ++Count;} FVehiclePhATBodyUtils::MarkAssetChanged(P); Msg=FString::Printf(TEXT("Mirrored %d bodies."),Count); return Count>0;}
