#include "VehiclePhATBodyUtils.h"
#include "VehiclePhATToolsLog.h"
#include "PhysicsEngine/PhysicsAsset.h"
#include "PhysicsEngine/SkeletalBodySetup.h"
#include "PhysicsEngine/BodySetup.h"
#include "PhysicsEngine/AggregateGeom.h"
#include "PhysicsEngine/PhysicsConstraintTemplate.h"
#include "Editor.h"
#include "Engine/Selection.h"

UPhysicsAsset* FVehiclePhATBodyUtils::GetSelectedPhysicsAsset(){ TArray<UPhysicsAsset*> Assets=GetSelectedPhysicsAssets(); return Assets.Num()?Assets[0]:nullptr; }
TArray<UPhysicsAsset*> FVehiclePhATBodyUtils::GetSelectedPhysicsAssets(){ TArray<UPhysicsAsset*> R; if(!GEditor)return R; USelection* Sel=GEditor->GetSelectedObjects(); for(FSelectionIterator It(*Sel); It; ++It) if(UPhysicsAsset* P=Cast<UPhysicsAsset>(*It)) R.Add(P); return R; }
USkeletalBodySetup* FVehiclePhATBodyUtils::FindBodySetup(UPhysicsAsset* P,FName B,int32* I){ if(I)*I=INDEX_NONE; if(!P)return nullptr; for(int32 N=0;N<P->SkeletalBodySetups.Num();++N){USkeletalBodySetup* S=P->SkeletalBodySetups[N]; if(S&&S->BoneName==B){if(I)*I=N; return S;}} return nullptr; }
int32 FVehiclePhATBodyUtils::FindBodySetupIndex(UPhysicsAsset* P,FName B){int32 I; FindBodySetup(P,B,&I); return I;}
int32 FVehiclePhATBodyUtils::GetShapeCount(const FKAggregateGeom& Gm){return Gm.SphereElems.Num()+Gm.BoxElems.Num()+Gm.SphylElems.Num()+Gm.TaperedCapsuleElems.Num()+Gm.ConvexElems.Num();}
bool FVehiclePhATBodyUtils::HasAnyShape(const USkeletalBodySetup* B){return B&&GetShapeCount(B->AggGeom)>0;}
TArray<FName> FVehiclePhATBodyUtils::GetSkeletonBoneNames(const UPhysicsAsset* P){TArray<FName> R; if(!P||!P->PreviewSkeletalMesh)return R; const FReferenceSkeleton& S=P->PreviewSkeletalMesh->GetRefSkeleton(); for(int32 I=0;I<S.GetNum();++I)R.Add(S.GetBoneName(I)); return R;}
void FVehiclePhATBodyUtils::RefreshPhysicsAsset(UPhysicsAsset* P){ if(P){ P->UpdateBodySetupIndexMap(); P->InvalidateAllPhysicsMeshes(); }}
void FVehiclePhATBodyUtils::MarkAssetChanged(UPhysicsAsset* P){ if(P){ RefreshPhysicsAsset(P); P->MarkPackageDirty(); }}
TArray<FVehiclePhATValidationMessage> FVehiclePhATBodyUtils::ValidatePhysicsAsset(UPhysicsAsset* P,const FString& Src,const FString& Dst){TArray<FVehiclePhATValidationMessage> M; if(!P){M.Add({FVehiclePhATValidationMessage::ESeverity::Error,TEXT("No PhysicsAsset selected.")});return M;} TSet<FName> Bodies; for(USkeletalBodySetup* B:P->SkeletalBodySetups){ if(!B){M.Add({FVehiclePhATValidationMessage::ESeverity::Error,TEXT("Null body setup entry.")});continue;} Bodies.Add(B->BoneName); if(!HasAnyShape(B))M.Add({FVehiclePhATValidationMessage::ESeverity::Warning,FString::Printf(TEXT("Body '%s' has no shapes."),*B->BoneName.ToString())}); } for(FName Bone:GetSkeletonBoneNames(P)){ if(!Bodies.Contains(Bone)) M.Add({FVehiclePhATValidationMessage::ESeverity::Info,FString::Printf(TEXT("Bone '%s' has no body."),*Bone.ToString())}); } TSet<FString> C; for(UPhysicsConstraintTemplate* T:P->ConstraintSetup){ if(!T)continue; FName A=T->DefaultInstance.ConstraintBone1, B=T->DefaultInstance.ConstraintBone2; if(!Bodies.Contains(A)||!Bodies.Contains(B))M.Add({FVehiclePhATValidationMessage::ESeverity::Warning,FString::Printf(TEXT("Constraint '%s' references missing body."),*T->GetName())}); FString K=A.LexicalLess(B)?A.ToString()+TEXT("|")+B.ToString():B.ToString()+TEXT("|")+A.ToString(); if(C.Contains(K))M.Add({FVehiclePhATValidationMessage::ESeverity::Warning,FString::Printf(TEXT("Duplicated constraint between %s and %s."),*A.ToString(),*B.ToString())}); C.Add(K);} return M;}
bool FVehiclePhATBodyUtils::CopyBodySetupProperties(const USkeletalBodySetup* S,USkeletalBodySetup* T){ if(!S||!T)return false; FName Bone=T->BoneName; FKAggregateGeom Agg=T->AggGeom; T->CopyBodyPropertiesFrom(S); T->BoneName=Bone; T->AggGeom=Agg; return true; }
bool FVehiclePhATBodyUtils::CopyBodyShapeSettings(const USkeletalBodySetup* S,USkeletalBodySetup* T,EVehiclePhATShapeMismatchPolicy Pol,FString& Msg){ if(!S||!T){Msg=TEXT("Invalid body.");return false;} bool Same=GetShapeCount(S->AggGeom)==GetShapeCount(T->AggGeom); if(!Same&&Pol==EVehiclePhATShapeMismatchPolicy::SkipIncompatible){Msg=TEXT("Shape count mismatch; skipped.");return false;} if(Pol==EVehiclePhATShapeMismatchPolicy::ReplaceShapes||Same){T->AggGeom=S->AggGeom; Msg=TEXT("Shapes replaced/copied."); return true;} int32 N; N=FMath::Min(S->AggGeom.BoxElems.Num(),T->AggGeom.BoxElems.Num()); for(int32 i=0;i<N;++i){auto Tr=T->AggGeom.BoxElems[i].GetTransform(); T->AggGeom.BoxElems[i]=S->AggGeom.BoxElems[i]; T->AggGeom.BoxElems[i].SetTransform(Tr);} N=FMath::Min(S->AggGeom.SphereElems.Num(),T->AggGeom.SphereElems.Num()); for(int32 i=0;i<N;++i){auto C=T->AggGeom.SphereElems[i].Center; T->AggGeom.SphereElems[i]=S->AggGeom.SphereElems[i]; T->AggGeom.SphereElems[i].Center=C;} N=FMath::Min(S->AggGeom.SphylElems.Num(),T->AggGeom.SphylElems.Num()); for(int32 i=0;i<N;++i){auto Tr=T->AggGeom.SphylElems[i].GetTransform(); T->AggGeom.SphylElems[i]=S->AggGeom.SphylElems[i]; T->AggGeom.SphylElems[i].SetTransform(Tr);} Msg=TEXT("Common primitive shape settings applied."); return true;}
bool FVehiclePhATBodyUtils::CopyShapeTransforms(const USkeletalBodySetup* S,USkeletalBodySetup* T,bool L,bool R,bool E,bool All,FString& Msg){ if(!S||!T)return false; auto CopyTr=[&](auto& D,const auto& Src){FTransform DT=D.GetTransform(), ST=Src.GetTransform(); if(L)DT.SetLocation(ST.GetLocation()); if(R)DT.SetRotation(ST.GetRotation()); D.SetTransform(DT);}; int32 N=All?FMath::Min(S->AggGeom.BoxElems.Num(),T->AggGeom.BoxElems.Num()):FMath::Min(1,FMath::Min(S->AggGeom.BoxElems.Num(),T->AggGeom.BoxElems.Num())); for(int32 i=0;i<N;++i){CopyTr(T->AggGeom.BoxElems[i],S->AggGeom.BoxElems[i]); if(E){T->AggGeom.BoxElems[i].X=S->AggGeom.BoxElems[i].X;T->AggGeom.BoxElems[i].Y=S->AggGeom.BoxElems[i].Y;T->AggGeom.BoxElems[i].Z=S->AggGeom.BoxElems[i].Z;}} N=All?FMath::Min(S->AggGeom.SphereElems.Num(),T->AggGeom.SphereElems.Num()):FMath::Min(1,FMath::Min(S->AggGeom.SphereElems.Num(),T->AggGeom.SphereElems.Num())); for(int32 i=0;i<N;++i){if(L)T->AggGeom.SphereElems[i].Center=S->AggGeom.SphereElems[i].Center; if(E)T->AggGeom.SphereElems[i].Radius=S->AggGeom.SphereElems[i].Radius;} N=All?FMath::Min(S->AggGeom.SphylElems.Num(),T->AggGeom.SphylElems.Num()):FMath::Min(1,FMath::Min(S->AggGeom.SphylElems.Num(),T->AggGeom.SphylElems.Num())); for(int32 i=0;i<N;++i){CopyTr(T->AggGeom.SphylElems[i],S->AggGeom.SphylElems[i]); if(E){T->AggGeom.SphylElems[i].Radius=S->AggGeom.SphylElems[i].Radius;T->AggGeom.SphylElems[i].Length=S->AggGeom.SphylElems[i].Length;}} Msg=TEXT("Shape transform pasted."); return true;}
